name             'trash-cli'
maintainer       'byplayer'
maintainer_email 'byplayer100@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures trash-cli'
long_description 'Installs/Configures trash-cli'
version          '0.1.0'
